<script setup lang="ts">
import { toast } from "vue-sonner";
import {
  dockerService,
  type DockerTraefikSnapshot,
} from "~/services/dockerService";

interface Props {
  serverId: string;
}
const props = defineProps<Props>();

const snap = ref<DockerTraefikSnapshot | null>(null);
const isLoading = ref(true);
const isSaving = ref(false);

// Files come back as a name → content map. Sort alphabetically so the
// list is stable across refetches.
const fileList = computed(() => {
  if (!snap.value) return [] as string[];
  return Object.keys(snap.value.dynamic_files).sort((a, b) =>
    a.localeCompare(b),
  );
});

const selectedName = ref<string | null>(null);
// Locked = read-only (default). Unlocking enables the editor and
// reveals the Update button. Mirrors dokploy's pattern.
const locked = ref(true);
// Editor draft. Initialised from snap whenever the selected file
// changes; saved back via writeTraefikFile.
const draft = ref("");
// Track whether the user has edited since loading the file so we can
// avoid no-op POSTs to the API.
const isDirty = computed(() => {
  if (!snap.value || !selectedName.value) return false;
  return draft.value !== (snap.value.dynamic_files[selectedName.value] ?? "");
});

const fetchSnap = async () => {
  try {
    const res = await dockerService.host.traefik(props.serverId);
    snap.value = res.data;
    // Keep the currently-selected file if it still exists; otherwise
    // fall back to the first one.
    if (
      selectedName.value &&
      snap.value.dynamic_files[selectedName.value] !== undefined
    ) {
      draft.value = snap.value.dynamic_files[selectedName.value];
    } else {
      selectedName.value = fileList.value[0] ?? null;
      draft.value = selectedName.value
        ? snap.value.dynamic_files[selectedName.value]
        : "";
    }
  } catch (err: unknown) {
    const e = err as { data?: { message?: string } };
    toast.error(e.data?.message || "Failed to load Traefik config");
  } finally {
    isLoading.value = false;
  }
};

const selectFile = (name: string) => {
  // Switching files while there are unsaved edits would silently lose
  // them; confirm before discarding.
  if (isDirty.value) {
    const proceed = window.confirm(
      "Discard unsaved changes and switch files?",
    );
    if (!proceed) return;
  }
  selectedName.value = name;
  draft.value = snap.value?.dynamic_files[name] ?? "";
  locked.value = true; // re-lock on file switch so a focus-out doesn't keep edit mode hot.
};

// Auto-managed = the file is regenerated by Launch when application
// domains change. Naming convention from launch-go's Traefik dynamic
// writer is `<project>-<app>.yml`; everything else (custom-*.yml,
// middlewares.yml, anything the user dropped in) is user-owned.
const isAutoManaged = (name: string): boolean => {
  // Exclude well-known user-owned filenames first.
  if (name === "middlewares.yml") return false;
  if (name.startsWith("custom-")) return false;
  if (name.startsWith("user-")) return false;
  // Heuristic: Launch's auto-named files have at least one dash in
  // them and end .yml. Not perfect, but safe — the warning is just an
  // FYI banner, not a block.
  return /^[a-z0-9]+(-[a-z0-9]+)+\.yml$/i.test(name);
};

const save = async () => {
  if (!selectedName.value) return;
  isSaving.value = true;
  try {
    await dockerService.host.writeTraefikFile(
      props.serverId,
      selectedName.value,
      draft.value,
    );
    toast.success("Traefik file updated");
    // Update the local snapshot so isDirty resets without a refetch.
    if (snap.value) {
      snap.value.dynamic_files[selectedName.value] = draft.value;
    }
    locked.value = true;
  } catch (err: unknown) {
    const e = err as { data?: { message?: string } };
    toast.error(e.data?.message || "Failed to update Traefik file");
  } finally {
    isSaving.value = false;
  }
};

const cancel = () => {
  // Snap back to the on-disk contents and re-lock.
  if (snap.value && selectedName.value) {
    draft.value = snap.value.dynamic_files[selectedName.value] ?? "";
  }
  locked.value = true;
};

onMounted(fetchSnap);
</script>

<template>
  <div>
    <div class="mb-6">
      <h2 class="text-2xl font-semibold">Traefik</h2>
      <p class="mt-1 text-sm text-muted-foreground">
        Dynamic config for your apps. Launch writes one file per
        application domain; you can also add your own custom YAML
        (rate limits, custom middlewares, etc.).
      </p>
    </div>

    <div v-if="isLoading" class="flex items-center justify-center py-12">
      <Icon
        name="lucide:loader-2"
        class="h-6 w-6 animate-spin text-muted-foreground"
      />
    </div>

    <div
      v-else-if="!snap || fileList.length === 0"
      class="flex flex-col items-center justify-center rounded-lg border border-dashed py-16"
    >
      <Icon name="simple-icons:traefikproxy" class="h-12 w-12 text-muted-foreground" />
      <h3 class="mt-4 text-lg font-medium">No dynamic files yet</h3>
      <p class="mt-1 max-w-md text-center text-sm text-muted-foreground">
        Add a domain to one of your applications and a router config
        will appear here.
      </p>
    </div>

    <div
      v-else
      class="grid grid-cols-1 gap-4 lg:grid-cols-[260px_minmax(0,1fr)]"
    >
      <aside class="space-y-1 rounded-lg border bg-card p-2">
        <p
          class="px-2 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground"
        >
          Dynamic files ({{ fileList.length }})
        </p>
        <button
          v-for="name in fileList"
          :key="name"
          type="button"
          class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-xs transition-colors"
          :class="
            selectedName === name
              ? 'bg-primary/10 font-medium text-foreground'
              : 'hover:bg-muted/50'
          "
          @click="selectFile(name)"
        >
          <Icon
            :name="isAutoManaged(name) ? 'lucide:file-cog' : 'lucide:file-code'"
            class="h-3.5 w-3.5 shrink-0"
          />
          <span class="truncate font-mono">{{ name }}</span>
        </button>
      </aside>

      <section class="rounded-lg border bg-card">
        <header
          class="flex items-center justify-between gap-2 border-b px-4 py-3"
        >
          <div class="min-w-0">
            <p class="truncate font-mono text-xs">
              /etc/launch/traefik/dynamic/{{ selectedName }}
            </p>
            <p class="text-[11px] text-muted-foreground">
              {{
                selectedName && isAutoManaged(selectedName)
                  ? "Auto-managed by Launch — regenerated on next domain change."
                  : "User-managed YAML — preserved across deploys."
              }}
            </p>
          </div>
          <div class="flex items-center gap-2">
            <label class="flex items-center gap-2 text-xs text-muted-foreground">
              <Switch v-model="locked" />
              {{ locked ? "Locked" : "Edit mode" }}
            </label>
          </div>
        </header>

        <!--
          Always-on warning for auto-managed files. Visible even in
          locked / read-only mode so the user understands what they're
          looking at BEFORE deciding to unlock and edit — finding out
          mid-edit that the file gets overwritten is the worst time
          to learn it.
        -->
        <div
          v-if="selectedName && isAutoManaged(selectedName)"
          class="border-b border-amber-500/30 bg-amber-500/10 px-4 py-3 text-xs text-amber-900 dark:text-amber-200"
        >
          <Icon
            name="lucide:triangle-alert"
            class="mr-1 inline-block h-3.5 w-3.5 align-text-bottom"
          />
          This file is auto-generated by Launch — it'll be rewritten
          the next time you change domains for the matching
          application. For persistent custom routing rules, create a
          new file named <code>custom-*.yml</code> instead.
        </div>

        <!--
          SharedCodeEditor handles the actual editing; `disabled` is
          what flips it between read-only and editable. Same
          component the Scripts / Files / Deployment-settings pages
          use, so syntax highlighting and theme are consistent.
        -->
        <div class="p-4">
          <SharedCodeEditor
            v-model="draft"
            :disabled="locked"
            class="h-[480px]"
          />
        </div>

        <footer
          v-if="!locked"
          class="flex items-center justify-end gap-2 border-t bg-muted/20 px-4 py-3"
        >
          <Button
            type="button"
            variant="outline"
            :disabled="isSaving"
            @click="cancel"
          >
            Cancel
          </Button>
          <Button :disabled="isSaving || !isDirty" @click="save">
            <Icon
              v-if="isSaving"
              name="lucide:loader-2"
              class="mr-2 h-4 w-4 animate-spin"
            />
            Update
          </Button>
        </footer>
      </section>
    </div>
  </div>
</template>
